# Copyright 2026 Arkapravo Ghosh
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("features") {
  sources = [
    "ark_features.cc",
    "ark_features.h",
  ]
  public_deps = [ "//base" ]
}

source_set("ai_service") {
  sources = [
    "ark_ai_service.cc",
    "ark_ai_service.h",
    "ark_ai_service_factory.cc",
    "ark_ai_service_factory.h",
    "ark_conversation_store.cc",
    "ark_conversation_store.h",
    "ark_inference_service.cc",
    "ark_inference_service.h",
    "ark_model_manager.cc",
    "ark_model_manager.h",
    "ark_paths.cc",
    "ark_paths.h",
  ]
  deps = [
    "//base",
    "//components/download/public/common:public",
    "//chrome/browser/profiles:profile",
    "//components/keyed_service/core",
    "//content/public/browser",
    "//net",
    "//services/network/public/cpp",
    "//sql",
  ]
}
